### ISSUE TITLE
Don't show vehicle notes if there are no vehicles present

### ISSUE THREAD

**Issue by alexpetros** [dartmouth-outing-club/doc-trailhead#94]
From Elliot
> If we could change it so that folks can only add notes after they hit add vehicle, that would be awesome! Think folks are typing into the note section believing they are requesting a vehicle without actually hitting the "Add Vehicle" button.

Don't show notes section if there's no vehicles added to the trips.

**Comment by Ben-Bauer-15** [comment]
Assigning myself, work is done already.

**Comment by Ben-Bauer-15** [comment]
@alexpetros see PR

**Comment by alexpetros** [comment]
Thanks again for the help Ben
